version: "3.1"
services:
  node:
    build: ./
    volumes:
        - ./src:/code/src
    ports:
      # During local development, this should be changed to 80:80
      - "8080:80"
    environment:
      - VIRTUAL_HOST=travels.seppe.dev
      - LETSENCRYPT_HOST=travels.seppe.dev
    network_mode: bridge
