version: "3.1"
services:
  node:
    build: ./
    restart: always
    volumes:
        - ./src:/opt/travelmap/src
    environment:
      - VIRTUAL_HOST=travels.lenders.dev
      - LETSENCRYPT_HOST=travels.lenders.dev
    networks:
      - reverse-proxy


networks:
  reverse-proxy:
    external:
      name: reverse-proxy_external
