version: "3.1"
services:
  node:
    build: ./
    volumes:
        - ./src:/code/src
    # This should be enabled during local development
    # ports:
    #   - "80:80"
    environment:
      - VIRTUAL_HOST=travels.seppe.dev
      - LETSENCRYPT_HOST=travels.seppe.dev
    network_mode: bridge
