services:
  node:
    build: ./
    restart: unless-stopped
    volumes:
      - ./:/opt/travelmap
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.travelmap.rule=Host(`travels.lenders.dev`)"
      - "traefik.http.routers.travelmap.tls=true"
      - "traefik.http.routers.travelmap.tls.certresolver=myresolver"
