version: "3.1"
services:
  node:
    build: ./
    restart: always
    volumes:
        - ./src:/opt/travelmap/src
    # Enable this during local development
    ports:
      - "80:80"
    environment:
      - VIRTUAL_HOST=travels.lenders.dev
      - LETSENCRYPT_HOST=travels.lenders.dev
    networks:
      - reverse-proxy


networks:
  reverse-proxy:
    # Disable this during local development
    # external:
    #   name: reverse-proxy_external
