version: "3.1"
services:
  node:
    build: ./
    volumes:
        - ./src:/code/src
    ports:
      - "8080:8080"
    environment:
      - VIRTUAL_HOST=travels.seppe.dev
      - LETSENCRYPT_HOST=travels.seppe.dev
    network_mode: bridge
