import materialColors from 'material-colors';
import * as traveldata from './traveldata';
import { default as Travel, TravelType } from './Travel';



const travels: Array<Travel> = [
  new Travel(
    'torknoeter',
    'Torgny – Knokke',
    materialColors.red['600'],
    new Date(2010, 4, 11),
    new Date(2010, 4, 16),
    [TravelType.BIKING],
    traveldata.torknoeter,
  ),
  new Travel(
    'kopenhagen',
    'Kopenhagen',
    materialColors.purple['600'],
    new Date(2012, 9, 3),
    new Date(2012, 4, 21),
    [TravelType.BIKING],
    traveldata.kopenhagen,
  ),
  new Travel(
    'marseille',
    'Marseille',
    materialColors.yellow['600'],
    new Date(2013, 4, 1),
    new Date(2013, 4, 9),
    [TravelType.BIKING],
    traveldata.marseille,
  ),
  new Travel(
    'venetie',
    'Venetië',
    materialColors.teal['600'],
    new Date(2013, 8, 26),
    new Date(2013, 9, 13),
    [TravelType.BIKING],
    traveldata.venetie,
  ),
  new Travel(
    'italie-balkan',
    'Italië & Balkan',
    materialColors.pink['600'],
    new Date(2014, 2, 10),
    new Date(2014, 8, 10),
    [TravelType.BIKING],
    traveldata.italieBalkan,
  ),
  new Travel(
    'rome',
    'Basel – Rome',
    materialColors.lightGreen['600'],
    new Date(2015, 4, 3),
    new Date(2015, 4, 20),
    [TravelType.BIKING],
    traveldata.rome,
  ),
  new Travel(
    'schotland',
    'Schotland',
    materialColors.deepOrange['600'],
    new Date(2016, 6, 2),
    new Date(2016, 6, 20),
    [TravelType.BIKING],
    traveldata.schotland,
  ),
  new Travel(
    'roemenie',
    'Roemenië',
    materialColors.cyan['600'],
    new Date(2017, 8, 12),
    new Date(2017, 9, 2),
    [TravelType.BIKING],
    traveldata.roemenie,
  ),
  new Travel(
    'portugal',
    'Portugal',
    materialColors.orange['600'],
    new Date(2018, 5, 25),
    new Date(2018, 6, 16),
    [TravelType.HIKING],
    traveldata.portugal,
  ),
  new Travel(
    'pyreneeen',
    'Pyreneeën',
    materialColors.blue['600'],
    new Date(2018, 9, 13),
    new Date(2018, 9, 22),
    [TravelType.HIKING],
    traveldata.pyreneeen,
  ),
  new Travel(
    'noord-spanje',
    'Noord-Spanje',
    materialColors.indigo['600'],
    new Date(2019, 6, 13),
    new Date(2019, 7, 8),
    [TravelType.BIKING, TravelType.HIKING],
    traveldata.noordSpanje,
  ),
  new Travel(
    'mercantour',
    'Mercantour',
    materialColors.brown['600'],
    new Date(2019, 8, 6),
    new Date(2019, 8, 13),
    [TravelType.HIKING],
    traveldata.mercantour,
  ),
];
export default travels;
